config/routes.rb
Rails.application.routes.draw do

  resources :spendings
  resources :groups

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
      }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "groups#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/spending.rb
class Spending < ApplicationRecord
  belongs_to :user
  has_many :group_spendings, dependent: :delete_all
  has_many :groups, through: :group_spendings
  validates :name, presence: true
  validates :amount, presence: true
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  before_action :set_spending, only: %i[show edit update destroy]

  # GET /spendings or /spendings.json
  def index
    @spendings = Spending.where(user: current_user)
    @groups = Group.where(user: current_user)
    @total_spending = @spendings.all.sum(:amount)
  end

  # GET /spendings/1 or /spendings/1.json
  def show; end

  # GET /spendings/new
  def new
    @spending = current_user.spendings.new

    @groups = Group.where(user: current_user)
  end

  # GET /spendings/1/edit
  def edit
    @groups = Group.where(user: current_user)
  end

  # POST /spendings or /spendings.json
  def create
    @groups = Group.where(user: current_user)
    @spending = Spending.new(user_id: spending_params[:user_id], name: spending_params[:name],
                             amount: spending_params[:amount])

    respond_to do |format|
      if @spending.save
        params[:spending][:group_id].each do |group_id|
          puts group_id
          GroupSpending.create!(group_id: group_id.to_i, spending_id: @spending.id)
        end
        format.html { redirect_to spending_url(@spending), notice: 'Spending was successfully created.' }
        format.json { render :show, status: :created, location: @spending }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spending.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spendings/1 or /spendings/1.json
  def update
    respond_to do |format|
      if @spending.update(spending_params)
        format.html { redirect_to spending_url(@spending), notice: 'Spending was successfully updated.' }
        format.json { render :show, status: :ok, location: @spending }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spending.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spendings/1 or /spendings/1.json
  def destroy
    @spending.destroy

    respond_to do |format|
      format.html { redirect_to spendings_url, notice: 'Spending was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_spending
    @spending = Spending.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def spending_params
    params.require(:spending).permit(:name, :amount, :user_id, :group_id)
  end
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/views/spendings/_form.html.erb
<%= form_with(model: spending) do |form| %>
  <% if spending.errors.any? %>
  <div class="mt-5 alert d-flex justify-content-center">

      <h2 ><%= pluralize(spending.errors.count, "error") %> prohibited this spending from being saved:</h2>

      <ul>
        <% spending.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="d-flex flex-column align-items-center">
  <div class="field my-3"> 
    <%= form.label :name,class: "form-label"%>
    <%= form.text_field :name , class: "form-control"  %>
  </div>

  <div class="field my-3">
    <%= form.label :amount,class: "form-label" %>
    <%= form.text_field :amount , class: "form-control" %>
  </div>

  <div class="field my-3">
 <%= form.radio_button :user_id, "#{current_user.id}"  %>
<%= form.label :user_id, "Click to confirm name #{current_user.name}" ,class: "form-label" %>
  </div>
 <div class="field my-3">
    <% Group.where(user_id: current_user.id).each_with_index do |g , i| %>

              <%= form.check_box :group_id,  {multiple: true}, g.id, nil   %><%= g.name%>
        
    <% end %>
 </div>

 
  <div>
    <%= form.submit  class: "btn btn-primary" %>
  </div>
  </div>
<% end %>

app/views/spendings/_spending.html.erb
<div  class="my-3">
<%= link_to spending_path(spending.id), class:"text-decoration-none text-dark shadow d-flex mx-3 mt-3 align-items-center  " do %>
  <div class=" d-flex w-100 spend-h mx-3 justify-content-between align-items-center ">
  <p>
    <%= spending.name %>
  </p>

  <p>
    <%= spending.amount %>
  </p>
  </div>
<%end%>
</div>

app/views/spendings/edit.html.erb
<h1>Editing spending</h1>

<%= render "form", spending: @spending %>

<br>

<div>
  <%= link_to "Show this spending", @spending %> |
  <%= link_to "Back to spendings", spendings_path %>
</div>

app/views/spendings/index.html.erb
<div class="d-height d-flex flex-column justify-content-between" >

<%= render partial: "shared/navbar", locals: { title: "TRANSACTIONS" } %>
<br/>
  <% if @spendings.blank?%>
    <p class="text-center ">You don't have any tranasactions yet! Click below to add one.</p>
  <% else %>
  <div class="d-flex justify-content-end mx-3" >
  <span>$<%=@total_spending%></span>
  </div>
<div id="spendings"  class="mt-5 ">
  <% @spendings.each do |spending| %>
    <%= render spending %>
  <% end %>
</div>
<% end %>
<section class= "end">
<div class = "new-group d-flex justify-content-center">
<%= link_to "New Transaction", new_spending_path,  class: "btn btn-outline-light"%>
</div>
<section>

</div>

app/views/spendings/new.html.erb
<%= render partial: "shared/navbar", locals: { title: "TRANSACTIONS" } %>
<br/>
<div class= "my-3">
<%= render "form", spending: @spending %>
</div>

<br>

<div  class= "d-flex justify-content-center">
  <%= link_to "Back to Spendings", spendings_path, class: "btn" %>
</div>

app/views/spendings/show.html.erb
<%= render partial: "shared/navbar", locals: { title: "TRANSACTIONS" } %>
  <br/>
  <br/>
  <% if @spending.errors.any? %>
<p style="color: green"><%= notice %></p>
<%end%>
<div class="my-3">
<%= render @spending %>
</div>

<div class= "d-flex flex-column justify-content-center align-items-center my-5">
  <%= link_to "Back", spendings_path , class: "btn" %>

  <%= button_to "Delete this transaction", @spending, method: :delete  , class: "btn btn-danger" %>
</div>