config/routes.rb
Rails.application.routes.draw do

  resources :spendings
  resources :groups

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
      }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "groups#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/group.rb
class Group < ApplicationRecord
  include ImageUploader::Attachment(:image)
  belongs_to :user
  has_many :group_spendings, dependent: :delete_all
  has_many :spendings, through: :group_spendings
  validates :name, presence: true
  after_save :amount

  def amount
    result = 0
    spendings.each do |spending|
      result += spending.amount
    end
    result
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.where(user: current_user)
    @total_spending = Spending.where(user: current_user).sum(:amount)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = current_user.groups.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :image, :user_id, :group_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
<div class="mt-5 alert d-flex justify-content-center">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul class="list-unstyled">
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="d-flex flex-column align-items-center">
  <div class="field my-3">
    <%= form.label :name,class: "form-label" %>
    <%= form.text_field :name , class: "form-control",  placeholder: "Name"%>
  </div>

  <div class="field my-3">
   <%= image_tag form.object.image_url, class: "g-img image-thumbnail" if form.object.cached_image_data   %>
 <%= form.hidden_field :image, value: form.object.cached_image_data %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

<div class="field my-3">
<%= form.radio_button :user_id, "#{current_user.id}"  %>
<%= form.label :user_id, "Click to confirm name #{current_user.name}" ,class: "form-label" %>

</div>
  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="mt-3">
<%= link_to group_path(group.id), class:"text-decoration-none text-dark c-height shadow d-flex mx-3 mt-3 align-items-center  " do %>
   <div>
    <%= image_tag group.image_url, class:"g-img  img-thumbnail" if group.image %>
  </div>
  <div class=" d-flex w-100  mx-3 justify-content-between ">
  <div>
    <%= group.name %>
  </div>


    <div>
   <span>
   $  <%= group.amount %>
   </span>

  </div>
  </div>
<%end%>

 
 </div>  

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div class="d-height d-flex flex-column justify-content-between" >

<%= render partial: "shared/navbar", locals: { title: "CATEGORIES" } %>
<br/>
<%if user_signed_in?%>

  <% if @groups.blank?%>
    <p class="text-center">You don't have any category yet! Click below to add one.</p>
  <% else %>
<div id="groups" class="mt-5 ">
<div class="mx-3 d-flex justify-content-end ">
<span>$<%=@total_spending%></span>
</div>
  <% @groups.each do |group| %>
    <%= render group %>
  <% end %>
</div>

<%end%>
<section class= "end">
<div class = "new-group d-flex justify-content-center">
<%= link_to "New Category", new_group_path,  class: "btn btn-outline-light"%>
</div>
<section>
</div>
<%else%>
<div class="d-flex flex-column justify-content-end align-items-center log-in-container">
<div class="wrapper">
<h2 class="smart">Smart Budgets</h2>

</div>
<div class="d-flex flex-column mb-1 align-items-center">
 <%= button_to "SIGN IN", new_user_session_path, method: :get, class: "btn btn-primary" %>
 <%= button_to "SIGN UP", new_user_registration_path, method: :get, class: "btn " %>
</div>
</div>

<%end%>

app/views/groups/new.html.erb
<%= render partial: "shared/navbar", locals: { title: "NEW CATEGORIES" } %>
<br/>
<div class= "my-3">
<%= render "form", group: @group %>
</div>

<br>

<div  class= "d-flex justify-content-center">
  <%= link_to "Back to categories", groups_path, class: "btn" %>
</div>

app/views/groups/show.html.erb
<div class="d-height d-flex flex-column justify-content-between" >
<%= render partial: "shared/navbar", locals: { title: "CATEGORIES" } %>
<br/>
  <% if @group.errors.any? %>
<p style="color: green"><%= notice %></p>
<%end%>
<%= render @group %>

<div>
<div class= "d-flex flex-column justify-content-center align-items-center my-5">
  <%= link_to "Back to Category", groups_path, class: "btn" %>
  <%= button_to "Delete this Category", @group, method: :delete , class: "btn btn-danger" %>
</div>
  <section class= "end">
<div class = "new-group d-flex justify-content-center">
<%= link_to "ADD TRANSACTIONS", new_spending_path,  class: "btn btn-outline-light"%>
</div>
<section>
</div>
</div>